src/NLPModels.jl

I started from an old version and eventually duplicated previous changes. My actual version seems to work, but second derivatives in the new JuMP 0.12 are suspect. I still struggle to produce a small example of the trouble I get when solving iteratively a Brachistochrone model at iteration 107. This does not look as a NLPModels fault but rather comes from JuMP new AD implementation.
Once JuMP initializes to 0 the hv result in hprod, the temporary fix should be removed.

temporary fixes

---

src/NLPModels.jl
src/slack_model.jl
test/hs005.jl
test/hs010.jl
test/hs011.jl
test/hs014.jl
test/hs015.jl
test/runtests.jl
test/test_slack_model.jl

This pull request introduces the construction of a model that add slacks variables to an existing model.
@abelsiqueira

Slackmodel

---

.travis.yml
appveyor.yml
src/jump_model.jl
test/hs005.nl
test/hs010.nl
test/hs011.nl
test/hs014.nl
test/jump_vs_ampl.jl

Jump model fixes

---

src/jump_model.jl
src/slack_model.jl
test/consistency.jl

More consistency tests

---

src/NLPModels.jl
src/simple_model.jl
test/consistency.jl
test/genrose.jl
test/hs005.jl
test/hs006.jl
test/hs010.jl
test/hs011.jl
test/hs014.jl
test/runtests.jl
test/test_simple_model.jl

Implement SimpleNLPModel

---

.travis.yml
REQUIRE
src/simple_model.jl
test/genrose.jl
test/hs005.jl
test/hs006.jl
test/hs010.jl
test/hs011.jl
test/hs014.jl
test/test_simple_model.jl

This makes it much easier to create a simple model.
Since SimpleNLPModel is not intented for speed, this is good for the user.

Change SimpleNLPModel to use automatic differentiation

---

src/NLPModels.jl
src/jump_model.jl
src/simple_model.jl
test/consistency.jl
test/runtests.jl

This is built on top of #18 
I can rebase later.

Test cutest with counters

---

test/test_simple_model.jl

The previous test did not define any constraint.

Define constraint in simple_model test

---

REQUIRE
src/NLPModels.jl
test/consistency.jl
test/runtests.jl

new method: hess_op

---

src/NLPModels.jl
src/slack_model.jl
test/runtests.jl
test/test_slack_model.jl

Counters API

---

docs/mkdocs.yml
docs/src/index.md
docs/src/models.md
src/NLPModels.jl
src/autodiff_model.jl
src/simple_model.jl
test/brownden.jl
test/consistency.jl
test/genrose.jl
test/hs10.jl
test/hs11.jl
test/hs14.jl
test/hs5.jl
test/hs6.jl
test/runtests.jl
test/test_autodiff_model.jl
test/test_simple_model.jl

A very large PR, so a little explaining helps:
- ADNLPModel is the old SimpleNLPModel. It should be only a name change.
- SimpleNLPModel receives each NLPModels function (minus the nlp parameter).
- Then fixing every test to make it work.
- Finally the docs were updated, including change to orange.

Create ADNLPModel and change SimplNLPModel to be user defined only

---

src/nlp_to_mpb.jl

generic MPB interface

---

src/NLPModels.jl
test/consistency.jl
test/runtests.jl

Implements `jac_op`

---

src/autodiff_model.jl
src/mpb_model.jl
src/nlp_types.jl
src/simple_model.jl
test/runtests.jl
test/test_tools.jl

Types of problems

---

README.md
docs/src/index.md

Add Pkg.add on documentation

---

docs/src/api.md
src/NLPModels.jl
src/simple_model.jl
test/consistency.jl
test/hs10.jl
test/hs11.jl
test/hs14.jl
test/hs5.jl
test/hs6.jl
test/test_simple_model.jl

Add tools objcons and objgrad and implement for SimpleNLPModel

---

src/NLPModels.jl
test/consistency.jl

Check return values of the inplace functions

---

docs/make.jl

Also, the material theme we use changed a little.

Use 0.5 in docs instead of release

---

.travis.yml
appveyor.yml

#73 
Not sure of the syntax yet.

Allow failures on Julia 0.6

---

REQUIRE
src/nlp_types.jl
src/nlp_utils.jl
src/qn_model.jl
test/consistency.jl

Wait for https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/issues/30

Fix many deprecations warnings

---

src/autodiff_model.jl

Because Jacobians and Hessians returned by ForwardDiff are always dense arrays, using `sparse()` on them is not safe because the number of nonzeros and their location appears to change with the iterations. Until ForwardDiff returns sparse derivatives, I think we have no choice but store them as dense.

ForwardDiff only returns dense derivatives

---

src/feasibility_residual.jl

Add finalizer to FeasibilityResidual model that calls inner finalize

---

src/NLPModels.jl
src/NLSModels.jl
src/autodiff_model.jl
src/autodiff_nlsmodel.jl
src/feasibility_residual.jl
src/lls_model.jl
src/mpb_model.jl
src/qn_model.jl
src/simple_model.jl
src/simple_nls_model.jl
src/slack_model.jl
test/consistency.jl
test/runtests.jl

Create increment! function.
Erase counters(nlp) functions.

Update how counters work

---

src/simple_nls_model.jl
test/nls_consistency.jl
test/test_simple_nls_model.jl

Constraints on SimpleNLSModel

---

src/lls_model.jl
test/nls_consistency.jl

Add linear constraints to LLSModel

---

docs/make.jl
docs/src/api.md
docs/src/index.md
docs/src/models.md
docs/src/tools.md
src/NLPModels.jl
src/NLSModels.jl
src/autodiff_model.jl
src/autodiff_nlsmodel.jl

- Update to use 0.6
- Docs for NLSModels
- Docs for counters
- Docs for querying functions

Update the docs

---

REQUIRE
src/NLPModels.jl
src/NLSModels.jl
src/autodiff_model.jl
src/autodiff_nlsmodel.jl
src/feasibility_residual.jl
src/lls_model.jl
src/mpb_model.jl
src/nlp_to_mpb.jl
src/nlp_types.jl
src/nls_meta.jl
src/qn_model.jl
src/simple_model.jl
src/simple_nls_model.jl
src/slack_model.jl
test/runtests.jl
test/test_nlsmodels.jl

After https://github.com/JuliaLang/METADATA.jl/pull/14362

Update to struct and remove nullable

---

src/autodiff_model.jl

Modification of grad! function in ADNLPModels

---

REQUIRE

For https://github.com/JuliaLang/METADATA.jl/pull/17800#issuecomment-419236990

Upper bound Julia to before 1.0

---

REQUIRE
appveyor.yml
src/NLPModels.jl
src/NLSModels.jl
src/lls_model.jl
src/simple_nls_model.jl
test/test_lls_model.jl
test/test_simple_nls_model.jl

Additional changes to #133.
This PR targets the branch `julia-0.7`, so there is one additional step to see the build.
Let me know if you prefer something different, like a new PR superseeding #133, or a commit directly on branch `julia-0.7`.

Other Julia 0.7/1.0 updates

---

.travis.yml
REQUIRE
appveyor.yml
src/NLPModels.jl
src/NLSModels.jl
src/autodiff_nlsmodel.jl
src/feasibility_residual.jl
src/lls_model.jl
src/nlp_types.jl
src/simple_nls_model.jl
src/slack_model.jl
test/consistency.jl
test/hs11.jl
test/hs14.jl
test/nls_consistency.jl
test/runtests.jl
test/test_lls_model.jl
test/test_qn_model.jl
test/test_simple_nls_model.jl

suppress many (not all) Julia 0.7 warnings

phase out Julia 0.6

---

.travis.yml

So that documentation can be built.

Build tags on .travis

---

docs/Project.toml
docs/make.jl
docs/src/index.md
docs/src/models.md
src/simple_model.jl

Update docs checking for dead links

---

src/lls_model.jl
test/test_lls_model.jl

LLSModel constraints are linear

---

docs/src/index.md
docs/src/tutorial.md

Add Nonlinear Least Squares models to tutorial

---

src/slack_model.jl
test/runtests.jl
test/test_view_subarray.jl

Needs to be rebased after #115 ~~and #145~~.

 Improve testing for view subarray argument and related fixes

---

test/consistency.jl
test/nls_consistency.jl
test/test_feasibility_form_nls.jl
test/test_lls_model.jl
test/test_qn_model.jl
test/test_simple_model.jl
test/test_simple_nls_model.jl
test/test_slack_model.jl
test/test_view_subarray.jl

Remove all random tests

---

src/slack_model.jl

Add name to slack models

---

src/autodiff_nlsmodel.jl

Fix passing name to ADNLSModel

---

.zenodo.json

Adds contributors and license.

Fix zenodo.json

---

.travis.yml
REQUIRE
appveyor.yml
docs/src/tutorial.md
src/NLPModels.jl
src/autodiff_model.jl
src/autodiff_nlsmodel.jl
src/lls_model.jl
src/slack_model.jl
test/brownden.jl
test/consistency.jl
test/hs10.jl
test/hs11.jl
test/hs14.jl
test/hs5.jl
test/hs6.jl

Build after #167, needs to be rebased later - I'm using the new `Draft Pull Request`.
- Includes #168;
- Simple fix in slack model discovered while implemented the new models;
- The new models are implemented, one at each file;
- Simple documentation on (#170).

Create model for tests

---

test/consistency.jl
test/nls_consistency.jl

[skip ci] Add tests

---

src/lls_model.jl
test/test_lls_model.jl

[skip ci] Add coord-improvements to LLSModel

---

src/autodiff_model.jl
src/autodiff_nlsmodel.jl

[skip ci] Implement coord-improvements for AD models

---

test/brownden.jl
test/hs10.jl
test/hs11.jl
test/hs14.jl
test/hs5.jl
test/hs6.jl

[skip ci] Add coord-improvements to manual tests

---

src/feasibility_form_nls.jl
src/feasibility_residual.jl
src/qn_model.jl
src/slack_model.jl

[skip ci] Add coord-improvements to feasibility models, QN models and slack models

---

src/NLPModels.jl
src/NLSModels.jl
src/autodiff_model.jl
src/autodiff_nlsmodel.jl
src/feasibility_form_nls.jl
src/feasibility_residual.jl
src/lls_model.jl
src/qn_model.jl
src/slack_model.jl

Using with IPOPT required `AbstractVector{<: Integer}`.

Change AbstractVector{Int} to {<: Integer}

---

README.md
docs/src/api.md
src/NLPModels.jl
src/autodiff_model.jl
src/slack_model.jl
test/hs10.jl
test/hs11.jl
test/hs14.jl
test/hs6.jl
test/runtests.jl

Better definition of default methods, where non-`!`methods call the corresponding `!` methods.

Bang methods

---

src/autodiff_model.jl
src/slack_model.jl

#188 will allow to remove quite a bit of code here, in CUTEst and in AmplNLReader.

Simplify methods

---

src/autodiff_model.jl
src/autodiff_nlsmodel.jl
test/test_autodiff_model.jl

Remove Function type from ADNLPModel to accept other callables

---

Project.toml
src/NLPModels.jl
src/autodiff_model.jl
src/autodiff_nlsmodel.jl
src/dercheck.jl
src/feasibility_form_nls.jl
src/feasibility_residual.jl
src/lls_model.jl
src/slack_model.jl
test/brownden.jl
test/consistency.jl
test/hs10.jl
test/hs11.jl
test/hs14.jl
test/hs5.jl
test/hs6.jl
test/multiple-precision.jl
test/runtests.jl
test/test_memory_of_coord.jl
test/test_slack_model.jl
test/test_view_subarray.jl

~Blocked by #212, don't review yet.~
Closes #211

Split Hessian functions into two removing multipliers as keywords

---

src/NLPModels.jl
src/NLSModels.jl
src/autodiff_model.jl
src/autodiff_nlsmodel.jl
src/feasibility_form_nls.jl
src/feasibility_residual.jl
src/lls_model.jl
src/qn_model.jl
src/slack_model.jl
test/brownden.jl
test/consistency.jl
test/hs10.jl
test/hs11.jl
test/hs14.jl
test/hs5.jl
test/hs6.jl
test/nls_consistency.jl
test/runtests.jl
test/test_lls_model.jl
test/test_memory_of_coord.jl
test/test_nlsmodels.jl
test/test_view_subarray.jl

Blocked by #215, do not merge.
Closes #192

Remove rows and cols from coord functions

---

src/autodiff_model.jl
src/autodiff_nlsmodel.jl

Improve ForwardDiff related prod functions

---

test/test_autodiff_model.jl

https://github.com/JuliaLang/julia/blob/master/base/range.jl#L65

stop in range is not positional argument in Julia 1.0

---

.cirrus.yml
.travis.yml
src/slack_model.jl
test/test-breakage.jl
test/test_slack_model.jl

Fix types in slack model (fix #217)

---

test/nls_consistency.jl
test/nls_problems/lls.jl
test/nls_problems/mgh01.jl
test/nls_problems/nlshs20.jl
test/runtests.jl

Same as #228, but from inside the repo so that `test-breakage` tests are posted.
Closes #228.

Refactor tests

---

test/consistency.jl
test/problems/brownden.jl

Conflicts with #235  
Closes #230

Fix issue230

---

docs/Project.toml
docs/src/api.md
docs/src/index.md
docs/src/models.md
docs/src/tutorial.md
src/NLPModels.jl
src/NLSModels.jl
src/dercheck.jl
src/feasibility_form_nls.jl
src/feasibility_residual.jl
src/lls_model.jl
src/slack_model.jl

Closes #246, #250, #251
I'm building the docs.

Several doc fixes

---

docs/make.jl
docs/src/api.md
docs/src/guidelines.md
docs/src/index.md
docs/src/tutorial.md
src/nlp_utils.jl
src/qn_model.jl
src/slack_model.jl

Non-exhaustive, and can be updated after #245.

Create guidelines in docs

---

test/consistency.jl
test/problems/lincon.jl
test/runtests.jl

Implementation of the model used in `NLPModelsJuMP`.

Add NLP problem LINCON

---

test/nls_problems/nlslc.jl
test/runtests.jl

Add NLS problem NLSLC

---

src/NLPModels.jl
src/qn_model.jl

new method reset_data!() for models that store resettable data

---

src/lls_model.jl
test/consistency.jl
test/multiple-precision.jl
test/nls_problems/lls.jl
test/nls_problems/mgh01.jl
test/nls_problems/nlshs20.jl
test/problems/brownden.jl
test/problems/genrose.jl
test/problems/hs10.jl
test/problems/hs11.jl
test/problems/hs14.jl
test/problems/hs5.jl
test/problems/hs6.jl
test/problems/lincon.jl
test/runtests.jl

This will improve the printing on other packages, and shouldn't undo the changes of #255

Changing tests printing

---

Project.toml
test/problems/linsv.jl
test/runtests.jl
test/test_qn_model.jl
test/test_slack_model.jl

Add NLP model LINSV

---

src/nlp_types.jl
src/nls_meta.jl
src/slack_model.jl

Just the relevant changes:
```
Counters:
obj: ██⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 2       grad: █████████████████⋅⋅⋅ 17    
cons: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0       jcon: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0     
jgrad: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0        jac: ████████████████████ 20    
jprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0     jtprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0     
hess: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0      hprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0     
jhprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
```
```
Counters:
obj: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                grad: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
cons: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                jcon: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
jgrad: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0                 jac: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
jprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0              jtprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0
hess: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 0               hprod: ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ …
```

Using histogram printing of the counters

---

docs/src/guidelines.md

RegularizationModel.jl was fixed as well.
Closes #296

Update guidelines with show information

---

src/NLPModels.jl
src/qn_model.jl
test/test_qn_model.jl

Thanks @liuyxpp for finding this.
Closes #304

Fix objgrad on qnmodels

---

.github/auto-merge.yml

[skip ci] Test probot

---

test/nls_consistency.jl
test/nls_problems/lls.jl
test/nls_problems/mgh01.jl
test/nls_problems/nlshs20.jl
test/nls_problems/nlslc.jl

Add hessian functions in test problems, so that we can also test consistency for `hprod` of nls problems.

Improve hessian tests

---

.github/workflows/breakage.yml
test/test-breakage-deploy.jl
test/test-breakage.jl

~Trying to fix breakage tests on GitHub actions. May take a while until it's working.~ Went better than expected.
Closes #313

GitHub Actions Breakage tests

---

.github/workflows/breakage.yml
test/test-breakage-deploy.jl
test/test-breakage.jl

Breakage improvements

---

.github/workflows/breakage.yml

cf. @tmigot, related to our discussion yesterday.

Testing breakage changes

---

docs/make.jl
docs/src/api.md
docs/src/internals.md
docs/src/models.md
docs/src/tools.md
src/NLPModels.jl
src/nlp/counters.jl
src/nlp/meta.jl
src/nlp/show.jl
src/nlp/utils.jl
src/nls/counters.jl
src/nls/meta.jl
src/nls/show.jl

Change some comments to docstrings

---

src/nlp/api.jl
src/nls/api.jl

Return Symmetric Hessians

---

Project.toml
src/nlp/api.jl
src/nls/api.jl
test/nlp/api.jl
test/nls/api.jl

Has to be updated after https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/pull/180 is released and tagged.

Use new LinearOperators

---

.github/workflows/Documentation.yml
.github/workflows/ci.yml
.github/workflows/format_pr.yml
README.md
docs/src/guidelines.md

These changes were made automatically, please check before merging.

[AUTO] Change master to main

---

docs/src/index.md
docs/src/models.md
src/nlp/meta.jl

Remove everything related to integer variables, network constraints, and multiple objectives in the meta

Simplify meta

---

Project.toml
README.md

Following #372 to fix `AmplNLReader.jl`.

Version 0.17.2

---

docs/src/api.md
docs/src/guidelines.md
docs/src/index.md

Modify the doc following #379 #377

Add linear api in docs

---

src/nlp/meta.jl
src/nls/meta.jl
test/nlp/simple-model.jl
test/nls/tools.jl

Ensure compatibility between `lin` and `nlin`.

Change default `nln` in `NLPModelMeta`

---

src/nlp/show.jl
src/nlp/tools.jl
src/nls/show.jl

https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/issues/51

Use abstract type for meta API

---

Project.toml

https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/issues/51

Version 0.18.4

---

src/nlp/meta.jl
src/nls/meta.jl

#398 
For the `NLPModelMeta`, I copied what was in the Readme.

documentation meta

---

README.md
docs/src/index.md

Spell out NLP

---

src/nls/api.jl
test/nls/api.jl

Add a keyword to avoid recomputing residual

---

src/nlp/counters.jl

Update documentation reset!

---

docs/src/guidelines.md

Fix link to meta in guideline

---

Project.toml

Update in the return type assumption

Version 0.21

---

.github/workflows/ci.yml
src/nlp/api.jl

Improve cons! and jprod! implementation

---

src/nlp/api.jl
src/nls/api.jl

- `@.` has an overhead cost on GPU

Remove the macro @.
