JuliaSmoothOptimizers/NLPModels.jl

src/NLPModels.jl, src/jump_model.jl, src/mpb_model.jl, src/nlp_to_mpb.jl, test/REQUIRE, test/consistency.jl, test/runtests.jl, test/test_mpb.jl, test/test_slack_model.jl
`JuMPNLPModel` is now called `MathProgNLPModel` since JuMP is not strictly required. It is still possible to create a `MathProgNLPModel` from a `JuMP.Model`, and that's indeed the current way to create one.
The IPOPT test now seems irrelevant to this package.
=> Factor out JuMP

.travis.yml, appveyor.yml, src/NLPModels.jl, src/qn_model.jl, test/runtests.jl, test/test_qn_model.jl
A simple initial design for quasi-Newton models. Example
```julia
julia> using NLPModels
julia> model = SimpleNLPModel(x -> dot(x, x), zeros(2))
julia> qnmodel = LBFGSModel(model)  # or LSR1Model; optional memory argument
```
Differences with other types of models:
* `hess_coord()` is not implemented (the Hessian is typically dense)
* `hess()` ~~returns a `LinearOperator`~~ is not implemented
* `hprod()` applies the linear operator
I'll add tests when we agree on the design.
@abelsiqueira
=> Quasi-Newton Models

src/nlp_to_mpb.jl
This simple change allows us to retrieve evaluation counters from a `AbstractNLPModel` after calling a `MathProgBase` solver. It should have been this way since the beginning.
=> use evaluator that allows us to count evals

src/autodiff_model.jl
Certain solvers (i.e., KNITRO :roll_eyes:) supply m+n multipliers to evaluate the Hessian and Hessian-vector products, including multipliers associated to the bound constraints.
=> only use multipliers for general constraints

REQUIRE
For a last release before #111, which requires `LinearOperators 0.4.0`.
=> Last working version of LinearOperators is 0.3.1

test/nls_consistency.jl
These are some additional tests on the consistency of `LLSModel`:
- `SlackNLSModel` of `LLSModel` vs `SlackNLSModel` of `ADNLSModel`;
- `LLSModel` with matrix vs `LLSModel` with `LinearOperator`
Some large changes in `nls_consistency` are actually just additional `if` checking if some tests are to be excluded.
=> Improve LLS consistency checks

docs/src/api.md, docs/src/tools.md, src/NLSModels.jl, src/autodiff_nlsmodel.jl, src/feasibility_form_nls.jl, src/feasibility_residual.jl, src/lls_model.jl, src/simple_nls_model.jl, src/slack_model.jl, test/nls_consistency.jl, test/test_generic_coord.jl, test/test_lls_model.jl, test/test_nlsmodels.jl, test/test_simple_nls_model.jl, test/test_view_subarray.jl
New `hess_residual(nlp, x, v)` computes `\sum_{i=1}^{n_e} v_i \nabla^2 F_i(x)`, and increments `:neval_hess_residual`.
Old `hess_residual(nlp, x, i)` computes `\nabla^2 F_i(x)`, and now increments the new `:neval_ihess_residual`.
=> Create new hess_residual which computes sum of Hessians

src/NLPModels.jl, src/NLSModels.jl, src/slack_model.jl
The use of `.tprod` is not directly expected, so it wasn't passed. Also did the same for `hprod`, just in case.
Closes #162
=> LinearOpeators now have tprod

src/NLPModels.jl, src/NLSModels.jl
Rebasing into `coord-and-structure` to handle #160. After all PRs are merged into `coord-and-structure`, I'll open a PR which runs CI. **This doesn't run CI**.
Part 01 of 07.
=> [skip ci] Implement structure and inplace coordinate functions

docs/src/api.md, src/NLPModels.jl, src/NLSModels.jl, src/autodiff_model.jl, src/autodiff_nlsmodel.jl, src/feasibility_form_nls.jl, src/feasibility_residual.jl, src/lls_model.jl, src/slack_model.jl, test/brownden.jl, test/hs10.jl, test/hs11.jl, test/hs14.jl, test/hs5.jl, test/hs6.jl
When embedding an NLPModel into another (e.g., an augmented Lagrangian), it would be useful to be able to accumulate the structure into existing arrays.
=> New methods to obtain Hessian structure in place

src/NLPModels.jl, src/autodiff_model.jl, src/slack_model.jl
Thank you for your great packages! I'm using NLPModels, CUTEst, NLPModelsJuMP and SolverTools for my research and they saved me a lot of time. I just realized some math display issues in your documentations (e.g. [here](http://juliasmoothoptimizers.github.io/NLPModels.jl/latest/api/#NLPModels.hess) and [here](http://juliasmoothoptimizers.github.io/NLPModels.jl/latest/models/#SlackModel-1)). So I tried to fix the problem.
Changes include:
- display math: fixed issues mentioned above,
- inline math: replaced `\$` by ` `` `,
- latex: replaced latex commands by unicode symbols for better docstring in REPL.
I'm pretty new to julia as well as collaborating on github. Let me know if I did anything stupid.
Thanks.
=> Fix display math in docstrings.

.travis.yml
Might be interesting to have `isunix` instead of `islinux` for some packages, but NLPModels doesn't have any specific OS code. 
On Windows the coverage submission sends wrong filenames, which can't be explored (`src\NLPModels.jl` instead of `src/NLPModels.jl`).
=> Change coverage in travis to run only for one build

.travis.yml, test/test-breakage-deploy.jl, test/test-breakage.jl
Supercedes #232 
- This split the test-breakage into one test for each pkg/version, i.e., 14 parallel tests (not really, because there is a limit for free users, but better than the alternative);
- Each test pushes a commit to a branch `breakage-info` with its own information;
- An additional stage reads the branch and creates the report.
Closes #232
=> Test-breakage runs in parallel

test/multiple-precision.jl, test/problems/brownden.jl, test/problems/hs10.jl, test/problems/hs11.jl, test/problems/hs14.jl, test/problems/hs5.jl, test/problems/hs6.jl, test/runtests.jl, test/test-breakage-deploy.jl
Multiple precision is tested through a function now, so it tests an input problem,  instead of a fixed ADNLPModel. This allows the multiple precision tests to be used in other packages. Also run multiple precision tests in more models.
=> Refactor multiple precision tests and fix some multiple precision issues

.travis.yml
If the breakage doesn't run, it means it worked.
=> Don't test breakage on forks

docs/Project.toml, docs/src/api.md, src/NLPModels.jl, src/NLSModels.jl, src/nlp_utils.jl, src/qn_model.jl, src/slack_model.jl, test/consistency.jl, test/nls_consistency.jl
cf @dpo, @amontoison 
Create/modify:
1. `jprod!(nlp, rows, cols, vals, v, Jv)` and `jtprod!` - well defined
2. `jprod!(nlp, x, rows, cols, v, Jv)` and `jtprod!` - defaults to `jprod!(nlp, x, v, Jv)`
3. `hprod!(nlp, rows, cols, vals, v, Hv)` (this works for both unc and con) - well defined
4. `hprod!(nlp, x, rows, cols, v, Hv)` - defaults to `hprod!(nlp, x, v, Hv)`
5. `hprod!(nlp, x, y, rows, cols, v, Hv)` - defaults to `hprod!(nlp, x, y, v, Hv)`
6. `jac_op!(nlp, rows, cols, vals, Jv, Jtv)` - uses 1
7. `jac_op!(nlp, x, rows, cols, Jv, Jtv)` - call `vals = jac_coord` and uses 6
8. `jac_op!(nlp, x, Jv, Jtv)` - modified to call `rows, cols = jac_structure` and `vals = jac_coord` and uses 6
9. `hess_op!` has same cases as 6, 7, 8
10. `decrement!` is implemented for use in 7.
=> Create prod functions that accept structure

src/NLPModels.jl, src/NLSModels.jl, src/slack_model.jl, test/consistency.jl, test/multiple-precision.jl, test/problems/hs10.jl, test/problems/hs11.jl, test/problems/hs14.jl, test/problems/hs6.jl, test/runtests.jl
Fix missing `eltype(vals)` in #245 and other related multiple precision errors.
=> More multiple precision fixes

src/NLPModels.jl, src/NLSModels.jl, test/test_nlsmodels.jl
Is it possible to merge this before the release 0.12 of NLPModel? I will need it for `NLPModelJuMP`.
=> Add jth_hess_residual implementation

test/multiple-precision.jl
Check whether printing during multiple-precision tests fix the issue with Julia 1.1 failing.
=> Print during multiple-precision tests

src/nlp_utils.jl
Related to https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/pull/143 and to #263. The underlying quasi-Newton operator wasn't being properly reset.
=> reset! should call reset_data!

src/qn_model.jl
Currently, we can't set `scaling=true` for quasi-Newton models.
=> pass options through to Quasi-Newton operator

test/nls_problems/lls.jl, test/nls_problems/mgh01.jl, test/nls_problems/nlshs20.jl, test/nls_problems/nlslc.jl, test/problems/hs10.jl, test/problems/hs11.jl, test/problems/hs14.jl, test/problems/hs5.jl, test/problems/hs6.jl, test/problems/lincon.jl
I didn't remove `hess` for browden model because it was used for `hess_coord!` and `hprod!`.
=> Remove jth_hess_residual, hess and jac implementations for test models

test/nls_problems/mgh01.jl, test/nls_problems/nlshs20.jl
Linear residuals are placed before nonlinear residuals. It's what we already do with the constraints. We should be able to check the consistency of NLS models that make the distinction between linear and nonlinear residuals.
=> Update NLS examples with linear residuals

src/NLPModels.jl, src/NLSModels.jl, src/autodiff_model.jl, src/autodiff_nlsmodel.jl, test/runtests.jl, test/test_autodiff_model.jl, test/test_nlsmodels.jl
Following this idea: https://white.ucc.asn.au/2020/04/19/Julia-Antipatterns.html
I also noticed an unnecessary computation of Hessians in `ADNLPModel`, I guess from the time we computed the sparsity of the Hessian there.
=> Remove NotImplemented and use MethodError instead

docs/Project.toml, docs/make.jl, docs/src/models.md, docs/src/tutorial.md, src/autodiff_model.jl, src/autodiff_nlsmodel.jl, test/nls_problems/lls.jl, test/nls_problems/nlshs20.jl, test/nls_problems/nlslc.jl, test/problems/hs10.jl, test/problems/hs11.jl, test/problems/hs14.jl, test/problems/hs5.jl, test/problems/hs6.jl, test/problems/lincon.jl, test/problems/linsv.jl, test/runtests.jl, test/test_autodiff_model.jl, test/test_autodiff_nls_model.jl, test/test_feasibility_form_nls.jl, test/test_feasibility_nls_model.jl, test/test_memory_of_coord.jl, test/test_slack_model.jl, test/test_tools.jl, test/test_view_subarray.jl
The only problem with this is that `ADNLPModel(f, x0, c=c, lcon=lcon, ucon=ucon)` doesn't work out of the box now. It needs `ncon=ncon` too.
=> Add new constructors for ADNLP and ADNLS models

src/feasibility_form_nls.jl, test/test_feasibility_form_nls.jl
Related to #273
This add a parametric type to `FeasibilityFormNLS` so we can handle the sparsity structure of a FeasibilityFormNLS of an LLSModel.
In essence, this allows `ipopt(FeasibilityFormNLS(lls))`.
@chenwilliam77, can you try this?
=> FeasibilityFormNLS of an LLSModel should handle hess structure

test/consistency.jl, test/nls_consistency.jl, test/runtests.jl
~Waiting for #324, do not merge.~ Ready.
ghjvprod breaks a few other packages, so it is initially excluded from the API consistency tests.
=> Add exclude to consistent_nlps and defaults to ghjvprod

src/nlp/meta.jl, src/nls/meta.jl
With this PR and after updating the compatibilities of NLPModelsModifiers, SolverCore and QuadraticModels, I am able to create a QuadraticModel with ` CuArray{Float64, 1}` vectors.
=> Update default arguments for NLPModelMeta

src/nlp/api.jl, src/nls/api.jl, test/nlp/api.jl, test/nls/api.jl
I let:
```
jac_op!(nlp, x, rows, cols, Jv, Jtv)
hess_op!(nlp, x, rows, cols, Hv; obj_weight=1.0)
hess_op!(nlp, x, y, rows, cols, Hv; obj_weight=1.0)
```
and
```
jac_op_residual!(nls, x, rows, cols, Jv, Jtv)
```
in case initializing LinearOperators benefit from the structure.
=> Remove matrix-product with the structure only

Project.toml
#381 was breaking as it changes the way we select linear constraints.
Moreover, this release is the first step to set up the linear API.
=> Version 0.18.0 [Merge after #387]

src/nlp/counters.jl
I found while benchmarking that `increment!()` allocates 2 bytes each time. It seems inlining solves the issue.
=> inline increment! to avoid allocations

src/nlp/meta.jl
`findall` returns an error with an empty `CuVector`.
I was unable to create a NLPModelMeta without this modification.
=> hotfix gpu

src/nlp/api.jl
I encountered this when setting the linear API in NLPModelsJuMP https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/tree/add-linear-api
It is a bit strange that this wasn't tested in NLPModels.jl or NLPModelsTest.jl, so I will also open an issue about that.
=> Fix counters in `jprod!` and `jtprod!`

src/nlp/api.jl
Another bug. The shift in the rows was only valid when linear constraints are given first.
It now works with: 
- https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/tree/add-linear-API
- https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/tree/add-linear-api
- https://github.com/JuliaSmoothOptimizers/LLSModels.jl/tree/add-linearAPI
- https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/tree/add-linearAPI
=> Fix linear API 2

src/nlp/counters.jl
It was
```
julia> using NLPModels
julia> c = Counters();
julia> @time sum_counters(c);
0.079578 seconds (295.66 k allocations: 15.417 MiB, 9.01% gc time, 99.93% compilation time)
julia> @time sum_counters(c);
0.000021 seconds (15 allocations: 2.039 KiB)
```
and now becomes
```
julia> using NLPModels
julia> c = Counters();
julia> @time sum_counters(c);
0.008422 seconds (32.14 k allocations: 1.756 MiB, 99.74% compilation time)
julia> @time sum_counters(c);
0.000004 seconds
```
=> `sum_counters` without allocations

Project.toml
A minor release with the possibility of calling `obj` and `grad` allocation free for NLS problems.
=> Version 0.19.1

src/nlp/meta.jl
@dpo, I continue my road to fully integrate PartitionedVectors in PartiallySeparableNLPModels.
For that, I need to define a NLPMeta relying on PartitionedVectors.
The current constructor doesn't support PartitionedVector, even if I provide directly some PartitionedVectors x0, uvar, xvar..., the following code:
```julia
ifix = findall(lvar .== uvar)
ilow = findall((lvar .> T(-Inf)) .& (uvar .== T(Inf)))
iupp = findall((lvar .== T(-Inf)) .& (uvar .< T(Inf)))
irng = findall((lvar .> T(-Inf)) .& (uvar .< T(Inf)) .& (lvar .< uvar))
ifree = findall((lvar .== T(-Inf)) .& (uvar .== T(Inf)))
iinf = findall(lvar .> uvar)
```
cause errors.
This PR puts the NLPMeta constructor outside the struct, which allows to define a NLPMeta dedicated to PartitionedVectors in PartiallySeparableNLPModels.jl.
=> put NLPModelMeta constructor outside of struct

docs/src/models.md
Added details of `BlockNLPModels.jl` and `BlockNLPAlgorithms.jl` that implement `NLPModels.jl`'s API in the documentation.
=> add blocknlpmodels in the docs

src/nlp/api.jl
This would solve https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/issues/77
```
using NLPModels, NLPModelsModifiers, NLPModelsTest
nlp = NLSLC()
nls = FeasibilityFormNLS(nlp)
x = get_x0(nls)
y = get_y0(nls)
Jtv = similar(x)
jtprod!(nls, x, y, Jtv)
@allocated jtprod!(nls, x, y, Jtv) # 0
```
Connected to https://github.com/JuliaSmoothOptimizers/NLPModels.jl/issues/384 .
=> Avoid views in jtprod!

src/nlp/api.jl, src/nls/api.jl
In some places, we assume that the vectors are of type `Vector{T}` which is not necessary the case in practice.
Connected to #454
=> Remove `Vector` implicit assumption

src/nlp/api.jl
This unifies the behavior with `objcons`. Otherwise, we have the strange behavior of having `neval_cons(nlp) = 0` after calling objcons!.
=> Call cons! in objcons! for unconstrained

.gitignore, docs/Project.toml, docs/src/api.md, docs/src/guidelines.md, docs/src/index.md, docs/src/models.md, docs/src/tools.md, src/nlp/meta.jl, src/nls/meta.jl
This eliminates the inconsistency in `c_i = 0` vs `c_L <= c_i <= c_U` noted in #460.
It also:
- adds Manifest.toml to `.gitignore`
- standardizes on `y` rather than `λ` for Lagrange multipliers
- clarifies or polishes wording in various places
- adds `NLPModels` to `docs/Project.toml` (this is standard and might
allow simplification of your `workflow`s)
=> Documentation tweaks (fixes #460)

src/nlp/meta.jl
Added assertion error in [nlp/meta.jl](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/main/src/nlp/meta.jl) if ``nnzj`` does not match ``lin_nnzj+nln_nnzj``, resolving #448.
Also related to https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/issues/120 and possibly [CUTEst.jl](https://github.com/JuliaSmoothOptimizers/CUTEst.jl).
=> Error for nnzj mismatch

src/nlp/utils.jl, test/nlp/utils.jl
We discussed this in [NLPModelsModifiers#121](https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/issues/121). 
The macro `default_counters` should now add the field `counters` to `Model`.
I think this is the easiest solution. 
If you are ok with this, could we update this package version for compatibility with `NLPModelsModifiers.jl` ?
=> Add counters field in default counters macro

src/nlp/meta.jl, test/nlp/meta.jl
We discussed this in #469
Added a function allowing to copy a NLPModelMeta but with the allowance to change some fields. 
For example, if one wants to modify the number of nonzero entries of the Hessian of some nlp, (this can be the case when one wants to use a diagonal Quasi-Newton approximation of the Hessian for example), one can write
```
meta = NLPModelMeta(nlp.meta, nnzh = nlp.meta.nvar)
```
=> Add new NLPModelMeta constructor

src/nlp/meta.jl
=> Use `nnzj` for default `nln_nnzj`

src/nlp/api.jl
=> `objcons` call `objcons!`
